"""empty message

Revision ID: 2f316bce6902
Revises: a3e0344ff2fb
Create Date: 2020-10-20 20:40:39.024901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f316bce6902'
down_revision = 'a3e0344ff2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'gens')
    op.drop_column('artist', 'seeking')
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venue', 'gens')
    op.drop_column('venue', 'seeking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('gens', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'genres')
    op.add_column('artist', sa.Column('seeking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('gens', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_talent')
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
