"""empty message

Revision ID: a3e0344ff2fb
Revises: 211188d042fe
Create Date: 2020-10-20 02:48:50.551482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e0344ff2fb'
down_revision = '211188d042fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('gens', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artist', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('gens', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'seeking')
    op.drop_column('venue', 'gens')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'seeking')
    op.drop_column('artist', 'gens')
    op.drop_table('Shows')
    # ### end Alembic commands ###
